version: '3.7'

networks:
  ci-cd:
  gitea:

volumes:
  data-jenkins:
  data-nexus:
  data-gitea:
  data-mysql:

services:
  nginx:
    image: nginx:1.14-alpine-perl
    container_name: nginx
    restart: always
    deploy:
      replicas: 3
    ports:
    - 80:80
    - 8080:8080
    - 8081:8081
    - 8082:8082
    - 5000:5000
    volumes:
    - ./data/nginx/:/etc/nginx/
    - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./data/nginx/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd:ro
    networks:
    - ci-cd
  nexus:
    image: sonatype/nexus3:3.15.0
    container_name: nexus
    restart: always
    deploy:
      replicas: 3
    expose:
    - 8081
    - 5000
    networks:
    - ci-cd
    volumes:
    - data-nexus:/sonatype-work
    - data-nexus:/nexus-data
  jenkins:
    image: jenkinsci/blueocean:1.10.1
    container_name: jenkins
    restart: always
    deploy:
      replicas: 3
    expose:
    - 8080
    - 50000
    volumes:
    - data-jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - ci-cd
  gitea:
    image: gitea/gitea:1.7
    container_name: gitea
    restart: always
    deploy:
      replicas: 3
    expose:
    - 3000
    - 22
    depends_on:
    - mysql
    volumes:
    - data-gitea:/data
    networks:
    - ci-cd
    - gitea
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    deploy:
      replicas: 3
    expose:
    - 3306
    environment:
    - MYSQL_DATABASE=gitea
    - MYSQL_USER=gitea
    - MYSQL_PASSWORD=PZKJ352Wbnio4BH8MtLwfsugdunAm8
    - MYSQL_ROOT_PASSWORD=PZKJ352Wbnio4BH8MtLwfsugdunAm8
    volumes:
    - data-mysql:/var/lib/mysql
    networks:
    - gitea
