version: '3.7'

networks:
  integration:
    name: integration

volumes:
  data-nginx:
    name: data-nginx-integration

services:
  nginx:
    image: nginx:1.15.9-alpine
    container_name: nginx-integration
    restart: always
    ports:
    - 8080:8080
    volumes:
    - ./data/nginx/:/etc/nginx/
    - data-nginx:/data-nginx/logs
    networks:
    - integration